version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.31-node-browsers-legacy
      - image: circleci/postgres:10.6-alpine-ram
        environment: # environment variables for primary container
          POSTGRES_USER: postgres
          POSTGRES_DB: quizzicaldb_test
          POSTGRES_PASSWORD: test
    # directory where steps are run.
    working_directory: ~/app

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be save
      TEST_CONN_STRING: postgres://postgres:test@localhost:5432/quizzicaldb_test
    
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: |
          psql \
          -d $TEST_CONN_STRING \
          -c "CREATE TABLE categories(name VARCHAR(256) PRIMARY KEY,active BOOL NOT NULL DEFAULT FALSE);"
      - run: |
          psql \
          -d $TEST_CONN_STRING \
          -c "CREATE TABLE questions(id BIGSERIAL PRIMARY KEY,text TEXT NOT NULL,category VARCHAR(256) NOT NULL REFERENCES categories(name) ON DELETE cascade);"
      - run: |
          psql \
          -d $TEST_CONN_STRING \
          -c "CREATE TABLE choices(id BIGSERIAL PRIMARY KEY,text TEXT NOT NULL,correct BOOL NOT NULL DEFAULT false,question_id BIGSERIAL NOT NULL REFERENCES questions(id) ON DELETE cascade);"
      
      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: cargo install

      #  Polling the DB port to confirm it is open before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Run unit tests
          environment: # environment variables for the database url and path to migration files
            TEST_CONN_STRING: "postgres://postgres:test@localhost:5432/quizzicaldb_test"
            RUST_BACKTRACE: 1
          # Store the results of our tests in the $TEST_RESULTS directory
          command: |
            cargo test | tee ${TEST_RESULTS}/test.out

      - save_cache: # Store cache in the /app/pkg directory
          key: v1-pkg-cache
          paths:
            - "~/app/pkg"

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results